### ISSUE TITLE
typo rate problem

### ISSUE THREAD

**Issue by XinyeYang** [tigerchen52/LOVE#13]
Hi,
Recently, I used IMDB movie review data set to perform Bert_with_love classification task, but I found that the classification accuracy did not decrease with the increase of oov proportion, but would remain unchanged or even increase. For example:
![微信图片编辑_20240726081437](https://github.com/user-attachments/assets/4ab72b59-4fc7-49a0-b6c8-03002dcfb188)
The file typo_test_10-typo_test_90 was generated using get_random_attack() of attacks.py.
Could you tell me the reason?
Thank you.

**Comment by tigerchen52** [comment]
Sorry for the late reply! I was busy preparing a rebuttal this week. 

Regarding your question, I guess it is caused by the distinction of the IMDB dataset. I would suggest having a look at the corrupted samples. Also, it is useful to only attract keywords in the input (some stop words won't impact the prediction very much).

**Comment by XinyeYang** [comment]
Thanks for your answer, my approach is to randomly select each word in the dataset to attack, however, the selected word is likely to have little impact on the classification. Could you guide me on how to choose keywords for each line of text?

**Comment by tigerchen52** [comment]
Regarding the keywords 1) you can have a look at TF-IDF keyword extraction ([link](https://github.com/kavgan/nlp-in-practice/blob/master/tf-idf/Keyword%20Extraction%20with%20TF-IDF%20and%20SKlearn.ipynb)). It is possible to use other tools for keyword extraction 2) you can use gradients to find significant words, which is proposed by [Adv-BERT](https://arxiv.org/pdf/2003.04985). 

Note that it's useful to repeat the experiment on another dataset to validate whether you meet the same issue.

**Comment by XinyeYang** [comment]
Thank you very much for your guidance.！I know what to do now.
