### ISSUE TITLE
Scores

### ISSUE THREAD

**Issue by stephantul** [tigerchen52/LOVE#3]
Hi,

I was wondering how you got the intrinsic scores for KVQ-FH in Table 2. The scores reported in [their paper](https://aclanthology.org/N19-1353.pdf) (table 4) are much higher than the scores you report, and higher than the scores reported for LOVE.

Kind regards,
Stéphan

**Comment by stephantul** [comment]
I now see that you retrained KVQ-FH to be much smaller than the model they report. Sorry for the noise!

**Comment by tigerchen52** [comment]
> I now see that you retrained KVQ-FH to be much smaller than the model they report. Sorry for the noise!

There are several hyper-parameters in KVQ-FH, e.g., $F$ (top-F frequent subwords) and $H$ (hashing size) that control the model's size.
Here, we set the hyper-parameter ```hashing size H = 40K``` for comparison, and you can reproduce the scores by using their source code [https://github.com/losyer/compact_reconstruction](https://github.com/losyer/compact_reconstruction).
