### ISSUE TITLE
reproducing paper results with different typo probabilities

### ISSUE THREAD

**Issue by pestrstr** [tigerchen52/LOVE#4]
Hi!
I'm trying to reproduce results from your ACL22 paper for MLRC2022.
In your paper, you show that LOVE+FastText and LOVE+BERT achieve more robustness in OOV, with respect to their respective baselines.
However, I found no instructions on how to produce typos/a corrupted dataset, except for details provided in **Appendix B.3**, where you talk about simulating post-OCR errors.

Would you be able to provide more insights on simulated typos?
I also found these paths in **_extrinsic/rnn_ner/gen_vocab.py_**:
```python
    train_path = 'input/train.txt' 
    dev_path = 'typo_data/typo_dev.txt'
    test_path = 'typo_data/typo_test.txt'
    out_path = 'typo_data/typo_vocab.txt'
```
which make me believe that some folders or script for simulating typos are missing.
Thank you!

**Comment by tigerchen52** [comment]
> Hi! I'm trying to reproduce results from your ACL22 paper for MLRC2022. In your paper, you show that LOVE+FastText and LOVE+BERT achieve more robustness in OOV, with respect to their respective baselines. However, I found no instructions on how to produce typos/a corrupted dataset, except for details provided in **Appendix B.3**, where you talk about simulating post-OCR errors.
> 
> Would you be able to provide more insights on simulated typos? I also found these paths in **_extrinsic/rnn_ner/gen_vocab.py_**:
> 
> ```python
>     train_path = 'input/train.txt' 
>     dev_path = 'typo_data/typo_dev.txt'
>     test_path = 'typo_data/typo_test.txt'
>     out_path = 'typo_data/typo_vocab.txt'
> ```
> 
> which make me believe that some folders or script for simulating typos are missing. Thank you!

Hi,

Thanks for asking!

To add typos, you can use the function "get_random_attack" in the file ``attacks.py``;
To simulate post-OCR, you can use the function "ocr_aug" in the file ``attacks.py``

This paper also describes about how to add attacks: Combating Adversarial Misspellings with Robust Word Recognition

Note that there is a real-world dataset that contains OCR errors, CLEF-HIPE.

**Comment by pestrstr** [comment]
Got it, thank you for answering!
