### ISSUE TITLE
How can create Hard Negative Samples?

### ISSUE THREAD

**Issue by MingyuKim-2933** [tigerchen52/LOVE#5]
Hi,

I was wondering LOVE makes a hard negative sample that top-100 similar words are extracted from each target word,
So do you make hard negative samples for every target words in vector file?

And How can create the similar words by edit distance for each target words?
or could you please provide the hard negative sample file used in LOVE framework?

Thank you!

**Comment by tigerchen52** [comment]
Hi,

Thanks for asking! I added another file to address your issue `get_hard_negative_example.py`. You can use it for reference.
Let me know if you have additional questions.

Best,

Lihu

**Comment by MingyuKim-2933** [comment]
Thank you for your quick and kind response!
