### ISSUE TITLE
Train BERT Embedding

### ISSUE THREAD

**Issue by MingyuKim-2933** [tigerchen52/LOVE#9]
Hello! I am currently trying to reproduce the LOVE model,

The sentence **"For ease of implementation, we learn only from the words that are not separated into pieces."** in your paper.

As I understand, In the vocab.txt file you provided, you did not use special tokens (e.g. "[PAD]", "[UNK]") and separated words (e.g. ##ir, ##di).

Is my understanding correct?

Thank you!

**Comment by tigerchen52** [comment]
Hi,

Yes, your understanding is correct. We only use embeddings of single and complete words. Note that learning these embeddings can improve robustness for sentence-level tasks and we can only have marginal improvements for token-level tasks. Maybe you should try distilled embeddings for the latter.

**Comment by MingyuKim-2933** [comment]
Thank you for your answer!
